### ISSUE TITLE
HA Card example on the readme is missing the 'cards:'

### ISSUE THREAD

**Issue by geertmeersman** [myTselection/youfone_be#5]
```
type: vertical-stack
  - type: markdown
    content: >-
```
needs to be
```
type: vertical-stack
cards:
  - type: markdown
    content: >-
```
